export enum Role {
  ADMIN = "ADMIN",
  SALES = "SALES",
  WAREHOUSE = "WAREHOUSE",
  ACCOUNTS = "ACCOUNTS",
  GUEST = "GUEST"
}

export enum Permission {
  // User & RBAC Management
  USER_MANAGE = "USER_MANAGE",
  ROLE_MANAGE = "ROLE_MANAGE",

  // Customers & CRM
  CUSTOMER_VIEW = "CUSTOMER_VIEW",
  CUSTOMER_CREATE = "CUSTOMER_CREATE",
  CUSTOMER_UPDATE = "CUSTOMER_UPDATE",
  CUSTOMER_DELETE = "CUSTOMER_DELETE",
  FOLLOWUP_CREATE = "FOLLOWUP_CREATE",

  // Products & Catalog
  PRODUCT_VIEW = "PRODUCT_VIEW",
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",

  // Stock & Inventory
  STOCK_VIEW = "STOCK_VIEW",
  STOCK_CREATE = "STOCK_CREATE",

  // Sales Challans
  CHALLAN_VIEW = "CHALLAN_VIEW",
  CHALLAN_CREATE = "CHALLAN_CREATE",
  CHALLAN_UPDATE = "CHALLAN_UPDATE",
  CHALLAN_CONFIRM = "CHALLAN_CONFIRM",
  CHALLAN_CANCEL = "CHALLAN_CANCEL",

  // Invoices & Finance
  INVOICE_VIEW = "INVOICE_VIEW",
  INVOICE_CREATE = "INVOICE_CREATE",
  INVOICE_UPDATE = "INVOICE_UPDATE",

  // Reporting & Intelligence
  REPORT_VIEW = "REPORT_VIEW",
  DASHBOARD_VIEW = "DASHBOARD_VIEW",
  AUDIT_VIEW = "AUDIT_VIEW"
}

export enum CustomerType {
  RETAIL = "RETAIL",
  WHOLESALE = "WHOLESALE",
  DISTRIBUTOR = "DISTRIBUTOR"
}

export enum CustomerStatus {
  LEAD = "LEAD",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum MovementType {
  IN = "IN",
  OUT = "OUT"
}

export enum ChallanStatus {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED"
}

export enum InvoiceStatus {
  ISSUED = "ISSUED",
  PAID = "PAID",
  CANCELLED = "CANCELLED"
}

export enum AuditAction {
  LOGIN = "LOGIN",
  GUEST_LOGIN = "GUEST_LOGIN",
  GOOGLE_LOGIN = "GOOGLE_LOGIN",
  LOGOUT = "LOGOUT",
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  CUSTOMER_CREATED = "CUSTOMER_CREATED",
  CUSTOMER_UPDATED = "CUSTOMER_UPDATED",
  CUSTOMER_DELETED = "CUSTOMER_DELETED",
  FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED",
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  STOCK_IN = "STOCK_IN",
  STOCK_OUT = "STOCK_OUT",
  CHALLAN_CREATED = "CHALLAN_CREATED",
  CHALLAN_UPDATED = "CHALLAN_UPDATED",
  CHALLAN_CONFIRMED = "CHALLAN_CONFIRMED",
  CHALLAN_CANCELLED = "CHALLAN_CANCELLED",
  INVOICE_GENERATED = "INVOICE_GENERATED",
  INVOICE_UPDATED = "INVOICE_UPDATED"
}
