export enum Role {
  ADMIN = "ADMIN",
  SALES = "SALES",
  WAREHOUSE = "WAREHOUSE",
  ACCOUNTS = "ACCOUNTS"
}

export enum CustomerType {
  RETAIL = "RETAIL",
  WHOLESALE = "WHOLESALE",
  DISTRIBUTOR = "DISTRIBUTOR"
}

export enum CustomerStatus {
  LEAD = "LEAD",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum MovementType {
  IN = "IN",
  OUT = "OUT"
}

export enum ChallanStatus {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED"
}

export enum InvoiceStatus {
  ISSUED = "ISSUED",
  PAID = "PAID",
  CANCELLED = "CANCELLED"
}

export enum AuditAction {
  LOGIN = "LOGIN",
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  CUSTOMER_CREATED = "CUSTOMER_CREATED",
  CUSTOMER_UPDATED = "CUSTOMER_UPDATED",
  CUSTOMER_DELETED = "CUSTOMER_DELETED",
  FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED",
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  STOCK_IN = "STOCK_IN",
  STOCK_OUT = "STOCK_OUT",
  CHALLAN_CREATED = "CHALLAN_CREATED",
  CHALLAN_UPDATED = "CHALLAN_UPDATED",
  CHALLAN_CONFIRMED = "CHALLAN_CONFIRMED",
  CHALLAN_CANCELLED = "CHALLAN_CANCELLED",
  INVOICE_GENERATED = "INVOICE_GENERATED",
  INVOICE_UPDATED = "INVOICE_UPDATED"
}
